

stages:
  - test
  - testAVX
  - testVAES
  - testVAESF



test-java-code:
  stage: test
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" bc-lts-java  \"/workspace/bc-lts-java/ci/test_java.sh\""
  artifacts:
    when: always
    reports:
      junit:
        - "core/build/test-results/**/TEST-*.xml"
        - "prov/build/test-results/**/TEST-*.xml"
        - "jmail/build/test-results/**/TEST-*.xml"
        - "pg/build/test-results/**/TEST-*.xml"
        - "pkix/build/test-results/**/TEST-*.xml"
        - "mail/build/test-results/**/TEST-*.xml"
        - "util/build/test-results/**/TEST-*.xml"
        - "tls/build/test-results/**/TEST-*.xml"


test-code-avx:
  stage: testAVX
  needs: ["test-java-code"]
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" bc-lts-java \"/workspace/bc-lts-java/ci/test_avx.sh\""
  artifacts:
    when: always
    reports:
      junit:
        - "core/build/test-results/**/TEST-*.xml"
        - "prov/build/test-results/**/TEST-*.xml"
        - "jmail/build/test-results/**/TEST-*.xml"
        - "pg/build/test-results/**/TEST-*.xml"
        - "pkix/build/test-results/**/TEST-*.xml"
        - "mail/build/test-results/**/TEST-*.xml"
        - "util/build/test-results/**/TEST-*.xml"
        - "tls/build/test-results/**/TEST-*.xml"


test-code-vaes:
  stage: testVAES
  needs: ["test-java-code"]
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" bc-lts-java \"/workspace/bc-lts-java/ci/test_vaes.sh\""
  artifacts:
    when: always
    reports:
      junit:
        - "core/build/test-results/**/TEST-*.xml"
        - "prov/build/test-results/**/TEST-*.xml"
        - "jmail/build/test-results/**/TEST-*.xml"
        - "pg/build/test-results/**/TEST-*.xml"
        - "pkix/build/test-results/**/TEST-*.xml"
        - "mail/build/test-results/**/TEST-*.xml"
        - "util/build/test-results/**/TEST-*.xml"
        - "tls/build/test-results/**/TEST-*.xml"


test-code-vaesf:
  stage: testVAESF
  needs: ["test-java-code"]
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" bc-lts-java \"/workspace/bc-lts-java/ci/test_vaesf.sh\""
  artifacts:
    when: always
    reports:
      junit:
        - "core/build/test-results/**/TEST-*.xml"
        - "prov/build/test-results/**/TEST-*.xml"
        - "jmail/build/test-results/**/TEST-*.xml"
        - "pg/build/test-results/**/TEST-*.xml"
        - "pkix/build/test-results/**/TEST-*.xml"
        - "mail/build/test-results/**/TEST-*.xml"
        - "util/build/test-results/**/TEST-*.xml"
        - "tls/build/test-results/**/TEST-*.xml"


